### DISCUSSION TITLE
BUG Custom Box Shadow and Custom Box Shadow Color

### DISCUSSION THREAD

**Discussion by fahmiidris** [dcastil/tailwind-merge#496] [Help]
Hi everyone,

I'm facing an issue with custom box shadows and custom box shadow colors in my project. When I include both in the same className, it seems that the custom box shadow gets overridden or eliminated.

Has anyone encountered this issue before? Is there a way to use both custom box shadow and custom box shadow color without losing the box shadow?

Thanks in advance!

with tw-merge:
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/00ec59fc-82d5-49af-9ab7-dcf0644cf2ae">

with no tw-merge:
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/42cfbc77-6e56-4c48-990b-1ef444127861">

my tailwind config:
```css
boxShadow: {
    'no-blur-lowest': '1px 1px 0px 0px',
    'no-blur-low': '2px 2px 0px 0px',
    'no-blur-medium': '4px 4px 0px 0px',
    'no-blur-high': '8px 8px 0px 0px',
    'no-blur-highest': '16px 16px 0px 0px',},
boxShadowColor: {
    primary: 'hsl(var(--primary))',
},
```
