### ISSUE TITLE
Problem with applying outline utility classes in Tailwind CSS

### ISSUE THREAD

**Issue by Squiffles** [dcastil/tailwind-merge#387]
### Description

I'm encountering an issue with applying outline utility classes in Tailwind CSS. When using the `twMerge` utility function, I'm unable to consistently apply `outline-focusedWidth`, `outline-focusedColor` and `outline-offset-focusedOffset` classes to an element.

### Steps To Reproduce

`tailwind.config.js`:

```javascript
module.exports = {
  theme: {
    extend: {
      outlineColor: {
        focus: '#00A491',
      },
      outlineWidth: {
        focus: '2.5px',
      },
      outlineOffset: {
        focus: '1.7px',
      },
    },
  },
};
```

`Button.jsx`:

```javaScript
function Button () {
  return (
    <button className={twMerge("outline outline-focusedWidth outline-focusedColor outline-offset-focusedOffset")}>
      Click
    </button>
  )
}
```

### Expected Behaviour

On the browser, I expect the bundler to apply the following classes to the element:

1. `outline`:
    ```css
    .outline {
        outline-style: solid;
    }
    ```
2. `outline-focusedWidth`:
    ```css
    .outline-focusedWidth {
        outline-width: 2.5px;
    }
    ```
3. `outline-focusedColor`:
    ```css
    .outline-focusedColor {
        outline-color: #00A491;
    }
    ```
4. `outline-offset-focusedOffset`:
    ```css
    .outline-offset-focusedOffset {
        outline-offset: 1.7px;
    }
    ```

And render the following HTML:
```html
<button class="outline outline-offset-focusedOffset outline-focusedColor outline-focusedWidth">Click</button>
```

### Actual behaviour

Only the last class is applied. For instance, if I have this:
```javascript
<button className={twMerge("outline outline-focusedWidth outline-focusedColor outline-offset-focusedOffset")}>
```

The `outline-offset-focusedOffset` class is correctly applied, but the `outline-focusedWidth` and `outline-focusedColor` are not and this is rendered:
```html
<button class="outline outline-offset-focusedOffset">Click</button>
```

However, if I change the order:
```javascript
<button className={twMerge("outline outline-focusedWidth outline-offset-focusedOffset outline-focusedColor")}>
```

This is rendered:
```html
<button class="outline outline-focusedColor">Click</button>
```

**The `outline` class is always added, no matter the order.**

**Using the regular className prop:**
```javascript
<button className="outline outline-focusedWidth outline-focusedColor outline-offset-focusedOffset">Click</button>
```
works well and adds the four classes to the element in the final bundle. So, I suppose the issue is related to how twMerge manages the outline classes: `outline-<customClass>` and `outline-offset-<customClass>`.

### Workaround

Using arbitrary values for the outline when using twMerge:
```javascript
<button className={twMerge("outline outline-[2.5px] outline-[#00A491] outline-offset-[1.7px]")}>Click</button>
```
Correctly applies the 4 classes:
```html
<button class="outline outline-[2.5px] outline-[#00A491] outline-offset-[1.7px]">Click</button>
```

### Environment

- TypeScript version: 5.3.3
- React version: 18.2.0
- Vite version: 5.1.3
- Tailwind CSS version: 2.2.1

### Additional information

The same behaviour occurs when the classes are defined with the same name:

`tailwind.config.js`:

```javascript
module.exports = {
  theme: {
    extend: {
      outlineColor: {
        focus: '#00A491'
      },
      outlineWidth: {
        focus: '2.5px'
      },
    },
  },
};
```

Then, using the regular className prop:

```javascript
<button className="outline outline-focus outline-offset-focus">Click</button>
```

adds the 3 classes:

1. `outline`:
```css
.outline {
    outline-style: solid;
}
```

2. `outline-focus`:
```css
.outline-focus {
    outline-width: 2.5px;
}
.outline-focus {
    outline-color: #00A491;
}
```

3. `outline-offset-focus`:
```css
.outline-offset-focus {
    outline-offset: 1.7px;
}
```

But, using twMerge doesn't work:

```javascript
<button className={twMerge("outline outline-focus outline-offset-focus")}>Click</button>
```

And you have to choose which one to write last, whether `outline-focus` or `outline-offset-focus`.

Note that in this case if you choose to write "outline-focus" as the last:

```javascript
<button className={twMerge("outline outline-offset-focus outline-focus ")}>Click</button>
```

It will apply colour and width:

`outline-focus`:
```css
.outline-focus {
    outline-width: 2.5px;
}
.outline-focus {
    outline-color: #00A491;
}
```

However, this behaviour only occurs if the names for these custom properties are the same:
