### ISSUE TITLE
twMerge doesnt respect of custom variant on font and color configured in @theme

### ISSUE THREAD

**Issue by DrChai** [dcastil/tailwind-merge#561]
### Describe the bug
when className contains both custom color and fontSize created by adding to the @theme block:
```css
@theme {
  --text-tiny: 0.625rem; 
  --color-regal-blue: #243c5a; 
}
```
```js
twMerge('text-tiny text-regal-blue') // 'text-regal-blue'
```
### Environment

- tailwindcss@4.0.15

-  tailwind-merge@3.0.2
