### ISSUE TITLE
Incorrectly merges custom shadow utilities with different meanings (e.g., color vs text-shadow)

### ISSUE THREAD

**Issue by mauriciabad** [dcastil/tailwind-merge#574]
### Describe the bug

Custom `shadow`s are not differentiated between just the color or the text-shadow itself. This happens for all the shadows (`shadow`, `text-shadow`, `drop-shadow`) and may happen for other properties.

### To Reproduce

https://codesandbox.io/p/sandbox/tailwind-merge-playground-cssr35

```css
@theme {
  --text-shadow-custom-shadow: 0 0 16px rgb(0 0 0 / 0.5);
  --color-custom-color: #dff976;
}
```

```ts
twMerge('shadow-custom-shadow', 'shadow-custom-color')
```

### Expected behavior

`twMerge` returns `shadow-custom-color`, but it should return `shadow-custom-shadow shadow-custom-color`.

### Environment

_Latest version_

### Additional context

_None_
